# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import archive_pb2 as archive__pb2


class ArchiveStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Save = channel.unary_unary(
                '/biz.Archive/Save',
                request_serializer=archive__pb2.SaveRequest.SerializeToString,
                response_deserializer=archive__pb2.Reply.FromString,
                )
        self.CheckValid = channel.unary_unary(
                '/biz.Archive/CheckValid',
                request_serializer=archive__pb2.CheckValidRequest.SerializeToString,
                response_deserializer=archive__pb2.Reply.FromString,
                )


class ArchiveServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Save(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckValid(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArchiveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=archive__pb2.SaveRequest.FromString,
                    response_serializer=archive__pb2.Reply.SerializeToString,
            ),
            'CheckValid': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckValid,
                    request_deserializer=archive__pb2.CheckValidRequest.FromString,
                    response_serializer=archive__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biz.Archive', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Archive(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/biz.Archive/Save',
            archive__pb2.SaveRequest.SerializeToString,
            archive__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckValid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/biz.Archive/CheckValid',
            archive__pb2.CheckValidRequest.SerializeToString,
            archive__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
