# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import file_pb2 as file__pb2


class FileStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseXlsx = channel.unary_unary(
                '/utility.File/ParseXlsx',
                request_serializer=file__pb2.ParseXlsxRequest.SerializeToString,
                response_deserializer=file__pb2.Reply.FromString,
                )


class FileServicer(object):
    """Missing associated documentation comment in .proto file"""

    def ParseXlsx(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseXlsx': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseXlsx,
                    request_deserializer=file__pb2.ParseXlsxRequest.FromString,
                    response_serializer=file__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'utility.File', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class File(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def ParseXlsx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utility.File/ParseXlsx',
            file__pb2.ParseXlsxRequest.SerializeToString,
            file__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
